# Controller-Konfiguration für den H1 Roboter
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# Detaillierte Parameter für jeden Controller
# ------------------------------------------
unitree_h1_hardware_interface:
  ros__parameters:
    # Robot URDF
    urdf_path: /home/argo/programmier_stuff/UNI/ip/src/0_common/h1_description/urdf/h1_sim.urdf

    # Joint Names
    joints:
      - left_hip_yaw_joint
      - left_hip_roll_joint
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_joint
      - right_hip_yaw_joint
      - right_hip_roll_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_joint
      - torso_joint
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint


imu_sensor_broadcaster:
  ros__parameters:
    type: imu_sensor_broadcaster/IMUSensorBroadcaster
    sensor_name: h1_imu
    frame_id: imu_link
    use_nominal_orientation: true

    static_covariance_orientation: [
      0.01, 0.0,   0.0,
      0.0,   0.01, 0.0,
      0.0,   0.0,   0.01
    ]

    static_covariance_angular_velocity: [
      0.001, 0.0,   0.0,
      0.0,   0.001, 0.0,
      0.0,   0.0,   0.001
    ]

    static_covariance_linear_acceleration: [
      0.1,  0.0,  0.0,
      0.0,   0.1, 0.0,
      0.0,   0.0,  0.1
    ]


joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    name: joint_trajectory_controller
    # state_publish_rate: 100.0
    joints:
      - left_hip_yaw_joint
      - left_hip_roll_joint
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_joint
      - right_hip_yaw_joint
      - right_hip_roll_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_joint
      - torso_joint
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

    gains:
      torso_joint:                  {p: 600.0, i: 0.7, d: 20.0}
      left_hip_yaw_joint:           {p: 600.0, i: 0.7, d: 20.0}
      left_hip_roll_joint:          {p: 600.0, i: 0.7, d: 20.0}
      left_hip_pitch_joint:         {p: 600.0, i: 0.7, d: 20.0}
      left_knee_joint:              {p: 600.0, i: 0.7, d: 20.0}
      left_ankle_joint:             {p: 600.0, i: 0.7, d: 20.0}
      right_hip_yaw_joint:          {p: 600.0, i: 0.7, d: 20.0}
      right_hip_roll_joint:         {p: 600.0, i: 0.7, d: 20.0}
      right_hip_pitch_joint:        {p: 600.0, i: 0.7, d: 20.0}
      right_knee_joint:             {p: 600.0, i: 0.7, d: 20.0}
      right_ankle_joint:            {p: 600.0, i: 0.7, d: 20.0}
      left_shoulder_pitch_joint:    {p: 200.0, i: 0.5, d: 10.0}
      left_shoulder_roll_joint:     {p: 200.0, i: 0.5, d: 10.0}
      left_shoulder_yaw_joint:      {p: 200.0, i: 0.5, d: 10.0}
      left_elbow_joint:             {p: 200.0, i: 0.5, d: 10.0}
      right_shoulder_pitch_joint:   {p: 200.0, i: 0.5, d: 10.0}
      right_shoulder_roll_joint:    {p: 200.0, i: 0.5, d: 10.0}
      right_shoulder_yaw_joint:     {p: 200.0, i: 0.5, d: 10.0}
      right_elbow_joint:            {p: 200.0, i: 0.5, d: 10.0}


ekf_filter_node:
  ros__parameters:
    frequency: 100.0
    two_d_mode: false
    # publish_tf: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # debug: true
    # debug_out_file: "/home/argo/ekf_debug_output.txt"
    print_diagnostics: true

    imu0: /imu/data
    imu0_config: [false, false, false, # [x, y, z] - Position nicht vom IMU
                  true,  true,  true,  # [roll, pitch, yaw] - Orientierung vom IMU nutzen
                  false, false, false, # [vx, vy, vz]
                  true,  true,  true,  # [v_roll, v_pitch, v_yaw] - Winkelgeschwindigkeit nutzen
                  true,  true,  true] # [ax, ay, az] - Lineare Beschleunigung nutzen
    imu0_remove_gravitational_acceleration: true
    # dynamic_process_noise_covariance: true

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 20

    # acceleration_limits: [10.0, 10.0, 10.0, 20.0, 20.0, 20.0]
    # deceleration_limits: [-10.0, -10.0, -10.0, -20.0, -20.0, -20.0]
    initial_state: [
      0.0, 0.0, 1.0,  # Initiale Position (x, y, z)
      0.0, 0.0, 0.0,  # Initiale Orientierung (roll, pitch, yaw)
      0.0, 0.0, 0.0,  # Initiale Geschwindigkeit (vx, vy, vz)
      0.0, 0.0, 0.0,   # Initiale Winkelgeschwindigkeit (v_roll, v_pitch, v_yaw)
      0.0, 0.0, 0.0   # Initiale Winkelgeschwindigkeit (v_roll, v_pitch, v_yaw)
    ]


wbc:
  ros__parameters:
    type: wbc/WbcController
    urdf_path: /home/argo/programmier_stuff/UNI/ip/src/0_common/h1_description/urdf/h1_sim.urdf

    joints: 
      - left_hip_yaw_joint
      - left_hip_roll_joint
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_joint
      - right_hip_yaw_joint
      - right_hip_roll_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_joint
      - torso_joint
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
  
    contact_frame_names: 
      - left_ankle_link
      - right_ankle_link
      
    weights:
      com: 0.1
      force: 0.0001
      regularization: 1.0
      contact: 1000.0
    
    friction_coefficient: 0.7


mpc_node:
  ros__parameters:
    mpc:
      constraints:
        force_max: 350.0
      weights:
        q: [10.0, 10.0, 10.0, 
            10.0, 10.0, 10.0, 10.0,
            1.0, 1.0, 1.0,
            1.0, 1.0, 1.0,]
        r: [0.1, 0.1, 0.1,
            0.1, 0.1, 0.1]